### ISSUE TITLE
Issues for the capstone project from team#109, the-taipans

### ISSUE THREAD

**Issue by temesghentekeste** [expjazz/capstone-project#1]
Positive Aspects
 - The code for HTML and CSS is well written and the usage of SASS was a good concept
 - The aesthetics of the page and the selection of images was great
 - Footer design was professional

Negative Aspects
 - As the page deals with house rent animation was disrupting the entire functionality of the page so the page would be great if it is removed
- the label on the dropdown list should be changed to choose or select  instead of chose

**Comment by expjazz** [comment]
Thanks guys! I did the required changes.
